title: Sena Guvercinoglu # your name (or website title) here
logo: "2019-08-05 15/26/45.266.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Istanbul Sehir University
  Computer Science Studendt
  <br><br>
  Currently intern at TUBU ARGE
  <br><br>
  <a href="https://www.linkedin.com/in/sena-güvercinoğlu-a501ba170/"</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
